export const airports = [
    { code: "MJT", name: "Mytilene", country: "Greece" },
    { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", country: "United States" },
    { code: "LAX", name: "Los Angeles International Airport", country: "United States" },
    { code: "ORD", name: "O'Hare International Airport", country: "United States" },
    { code: "DFW", name: "Dallas/Fort Worth International Airport", country: "United States" },
    { code: "DXB", name: "Dubai International Airport", country: "United Arab Emirates" },
    { code: "HND", name: "Tokyo International Airport (Haneda)", country: "Japan" },
    { code: "CDG", name: "Charles de Gaulle Airport", country: "France" },
    { code: "PEK", name: "Beijing Capital International Airport", country: "China" },
    { code: "JFK", name: "John F. Kennedy International Airport", country: "United States" },
    { code: "IST", name: "Istanbul Atatürk Airport", country: "Turkey" },
    { code: "CAN", name: "Guangzhou Baiyun International Airport", country: "China" },
    { code: "PVG", name: "Shanghai Pudong International Airport", country: "China" },
    { code: "SYD", name: "Sydney Airport", country: "Australia" },
    { code: "ICN", name: "Incheon International Airport", country: "South Korea" },
    { code: "SFO", name: "San Francisco International Airport", country: "United States" },
    { code: "EWR", name: "Newark Liberty International Airport", country: "United States" },
    { code: "SHA", name: "Shanghai Hongqiao International Airport", country: "China" },
    { code: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", country: "Spain" },
    { code: "YYZ", name: "Toronto Pearson International Airport", country: "Canada" },
    { code: "MNL", name: "Ninoy Aquino International Airport", country: "Philippines" },
    { code: "SIN", name: "Singapore Changi Airport", country: "Singapore" },
    { code: "BKK", name: "Suvarnabhumi Airport", country: "Thailand" },
    { code: "CGK", name: "Soekarno–Hatta International Airport", country: "Indonesia" },
    { code: "KUL", name: "Kuala Lumpur International Airport", country: "Malaysia" },
    { code: "VIE", name: "Vienna International Airport", country: "Austria" },
    { code: "GRU", name: "São Paulo–Guarulhos International Airport", country: "Brazil" },
    { code: "LIM", name: "Jorge Chávez International Airport", country: "Peru" },
    { code: "MCO", name: "Orlando International Airport", country: "United States" },
    { code: "SVO", name: "Sheremetyevo International Airport", country: "Russia" },
    { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", country: "India" },
    { code: "CUN", name: "Cancún International Airport", country: "Mexico" },
    { code: "LGA", name: "LaGuardia Airport", country: "United States" },
    { code: "HEL", name: "Helsinki Airport", country: "Finland" },
    { code: "MIA", name: "Miami International Airport", country: "United States" },
    { code: "LGW", name: "Gatwick Airport", country: "United Kingdom" },
    { code: "DEN", name: "Denver International Airport", country: "United States" },
    { code: "MUC", name: "Munich Airport", country: "Germany" },
    { code: "IAH", name: "George Bush Intercontinental Airport", country: "United States" },
    { code: "AKL", name: "Auckland Airport", country: "New Zealand" },
    { code: "OSL", name: "Oslo Airport, Gardermoen", country: "Norway" },
    { code: "BOG", name: "El Dorado International Airport", country: "Colombia" },
    { code: "ARN", name: "Stockholm Arlanda Airport", country: "Sweden" },
    { code: "SCL", name: "Comodoro Arturo Merino Benítez International Airport", country: "Chile" },
    { code: "BLR", name: "Kempegowda International Airport", country: "India" },
    { code: "ZRH", name: "Zürich Airport", country: "Switzerland" },
    { code: "HKG", name: "Hong Kong International Airport", country: "China" },
    { code: "NRT", name: "Narita International Airport", country: "Japan" },
    { code: "LHR", name: "Heathrow Airport", country: "United Kingdom" },
    { code: "JNB", name: "O. R. Tambo International Airport", country: "South Africa" },
    { code: "GIG", name: "Rio de Janeiro–Galeão International Airport", country: "Brazil" },
    { code: "YVR", name: "Vancouver International Airport", country: "Canada" },
    { code: "MEL", name: "Melbourne Airport", country: "Australia" },
    { code: "EZE", name: "Ministro Pistarini International Airport", country: "Argentina" },
    { code: "LIS", name: "Lisbon Airport", country: "Portugal" },
    { code: "JED", name: "King Abdulaziz International Airport", country: "Saudi Arabia" },
    { code: "DEL", name: "Indira Gandhi International Airport", country: "India" },
    { code: "CPH", name: "Copenhagen Airport", country: "Denmark" },
    { code: "PRG", name: "Václav Havel Airport Prague", country: "Czech Republic" },
    { code: "ATH", name: "Eleftherios Venizelos International Airport", country: "Greece" },
    { code: "KIX", name: "Kansai International Airport", country: "Japan" },
    { code: "GVA", name: "Geneva Airport", country: "Switzerland" },
    { code: "OTP", name: "Henri Coandă International Airport", country: "Romania" },
    { code: "NCE", name: "Nice Côte d'Azur Airport", country: "France" },
    { code: "HAM", name: "Hamburg Airport", country: "Germany" },
    { code: "BUD", name: "Budapest Ferenc Liszt International Airport", country: "Hungary" },
    { code: "MXP", name: "Milan Malpensa Airport", country: "Italy" },
    { code: "BRU", name: "Brussels Airport", country: "Belgium" },
    { code: "GDL", name: "Guadalajara International Airport", country: "Mexico" },
    { code: "BOO", name: "Bodø Airport", country: "Norway" },
    { code: "TXL", name: "Berlin Tegel Airport", country: "Germany" },
    { code: "BNE", name: "Brisbane Airport", country: "Australia" },
    { code: "AMS", name: "Amsterdam Airport Schiphol", country: "Netherlands" },
    { code: "FRA", name: "Frankfurt Airport", country: "Germany" },
    { code: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", country: "Italy" },
    { code: "MEX", name: "Mexico City International Airport", country: "Mexico" },
    { code: "GMP", name: "Gimpo International Airport", country: "South Korea" },
    { code: "TPE", name: "Taiwan Taoyuan International Airport", country: "Taiwan" },
    { code: "DUS", name: "Düsseldorf Airport", country: "Germany" },
    { code: "BCN", name: "Barcelona–El Prat Airport", country: "Spain" }
  ];